# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=100, null=True),
        ),
    ]
